### ISSUE TITLE
dateTimeThisMonth's comment should be month?

### ISSUE THREAD

**Issue by mikeanan** [FakerPHP/fakerphp.github.io#43]
https://fakerphp.github.io/formatters/date-and-time/
echo $faker->dateTimeThisMonth('+12 days');
// a date somewhere in this **year**, with an upper bound of +12 days

Have no idea about adding document label...

**Comment by pimjansen** [comment]
Valid, can you raise PR?

**Comment by bramceulemans** [comment]
I'm thinking we should add the stale bot on this repository, too.

**Comment by pimjansen** [comment]
> I'm thinking we should add the stale bot on this repository, too.

Yeah good idea. And update this ourself it seems

**Comment by mikeanan** [comment]
> Valid, can you raise PR?

:p
not familiar with github's PR...
XD

**Comment by pimjansen** [comment]
Its already resolved :)
