### ISSUE TITLE
Outdated third party providers 

### ISSUE THREAD

**Issue by smknstd** [FakerPHP/fakerphp.github.io#50]
On third party providers list https://fakerphp.github.io/third-party/, many providers seem outdated because they have not updated their composer.json. The process for someone who tries to use one of these, to understand what's happening can be tedious and frustrating. Maybe we should move them in a specific section or something. What do you think ?

some examples:
- https://github.com/EmanueleMinotto/PlaceholdItProvider/blob/master/composer.json#L18
- https://github.com/bruceheller/images-generator/blob/master/composer.json#L17
- https://github.com/ottaviano/faker-gravatar/blob/master/composer.json#L17
- https://github.com/finwe/phpstan-faker/blob/master/composer.json#L30

**Comment by pimjansen** [comment]
These should be removed indeed. But its always messy to maintain this so ideas are always welcome
